# Generated by Django 4.0.3 on 2022-03-08 14:11

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='Data criação')),
                ('updatedAt', models.DateField(auto_now_add=True, verbose_name='Data atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='Data criação')),
                ('updatedAt', models.DateField(auto_now_add=True, verbose_name='Data atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('icon', models.CharField(max_length=30, verbose_name='Icone')),
                ('service', models.CharField(max_length=100, verbose_name='Serviço')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='Data criação')),
                ('updatedAt', models.DateField(auto_now_add=True, verbose_name='Data atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255)),
                ('biography', models.TextField(max_length=400)),
                ('facebook', models.CharField(default='#', max_length=255)),
                ('twitter', models.CharField(default='#', max_length=255)),
                ('instagram', models.CharField(default='#', max_length=255)),
                ('image', stdimage.models.StdImageField(upload_to='team_images', verbose_name='Imagem')),
                ('role', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
